### ISSUE TITLE
Could you share the requirements.txt file?

### ISSUE THREAD

**Issue by anirudhajitani** [cts198859/deeprl_network#6]
Could you tell me which version of Python, Tensorflow you are using for the code?

I am trying to run the basic CCAC setup without Sumo and I am getting the following errors:
Traceback (most recent call last):
  File "/network/home/jitanian/thesis/deeprl_network/spatio-temp/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 490, in apply_op
    preferred_dtype=default_dtype)
  File "/network/home/jitanian/thesis/deeprl_network/spatio-temp/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/network/home/jitanian/thesis/deeprl_network/spatio-temp/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 614, in _TensorTensorConversionFunction
    % (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype bool for Tensor with dtype int64: 'Tensor("nc/boolean_mask/Reshape_1:0", shape=(8,), dtype=int64)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 161, in <module>
    train(args)
  File "main.py", line 99, in train
    model = init_agent(env, config['MODEL_CONFIG'], total_step, seed)
  File "main.py", line 63, in init_agent
    total_step, config, seed=seed)
  File "/network/home/jitanian/thesis/deeprl_network/agents/models.py", line 196, in __init__
    total_step, seed, model_config)
  File "/network/home/jitanian/thesis/deeprl_network/agents/models.py", line 110, in _init_algo
    self.policy = self._init_policy()
  File "/network/home/jitanian/thesis/deeprl_network/agents/models.py", line 240, in _init_policy
    self.neighbor_mask, n_fc=self.n_fc, n_h=self.n_lstm)
  File "/network/home/jitanian/thesis/deeprl_network/agents/policies.py", line 198, in __init__
    self._init_policy(n_agent, neighbor_mask, n_h)
  File "/network/home/jitanian/thesis/deeprl_network/agents/policies.py", line 329, in _init_policy
    self.pi_fw, self.v_fw, self.new_states = self._build_net('forward')
  File "/network/home/jitanian/thesis/deeprl_network/agents/policies.py", line 287, in _build_net
    h, new_states = lstm_comm(ob, policy, done, self.neighbor_mask, self.states, 'lstm_comm')
  File "/network/home/jitanian/thesis/deeprl_network/agents/utils.py", line 192, in lstm_comm
    mi = tf.expand_dims(tf.reshape(tf.boolean_mask(out_m, masks[i]), [-1]), axis=0)
  File "/network/home/jitanian/thesis/deeprl_network/spatio-temp/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1117, in boolean_mask
    return _apply_mask_1d(tensor, mask)
  File "/network/home/jitanian/thesis/deeprl_network/spatio-temp/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1089, in _apply_mask_1d
    indices = squeeze(where(mask), squeeze_dims=[1])
  File "/network/home/jitanian/thesis/deeprl_network/spatio-temp/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 2326, in where
    return gen_array_ops.where(input=condition, name=name)
  File "/network/home/jitanian/thesis/deeprl_network/spatio-temp/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3824, in where
    result = _op_def_lib.apply_op("Where", input=input, name=name)
  File "/network/home/jitanian/thesis/deeprl_network/spatio-temp/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 513, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'input' of 'Where' Op has type int64 that does not match expected type of bool.

**Comment by anirudhajitani** [comment]
Also could you point me to the code (line number or file) where the spatial discount factor and distance is incorporated while calculating rewards (Eq (2) of the paper)?

**Comment by cts198859** [comment]
We used Python 3.5.2 and tensorflow 1.12.0. The spatial discount factor is used to compute A and R for each minibatch, inside `OnPolicyBuffer._add_s_R_Adv()` and `MultiAgentOnPolicyBuffer._add_s_R_Adv()` of `agents/utils.py`. Note a distance matrix is also needed when we initialize the replay buffer.
