### ISSUE TITLE
Errors pop out when running in ATSC net environment

### ISSUE THREAD

**Issue by Benjamin-eecs** [cts198859/deeprl_network#8]
There is sth wrong with the package "traci" and it stopped the training all the time.

2020-09-26 11:16:41,135 [INFO] Training: a dim [6, 4, 2, 2, 2, 4, 2, 4, 2, 5, 2, 2, 4, 2, 2, 4, 2, 3, 6, 3, 2, 4, 4, 4, 4, 4, 6, 3], agent dim: 28
2020-09-26 11:16:41,136 [INFO] Use cpu for pytorch...
2020-09-26 11:16:41,208 [ERROR] Can not find checkpoint for /home/liubo/deeprl_net/ia2c_net_1.0/model/
Loading configuration... done.
Error: Answered with error to command 0xc2: The phase duration must be given as an integer.
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    train(args)
  File "main.py", line 104, in train
    trainer.run()
  File "/home/liubo/deeprl_network/utils.py", line 218, in run
    ob, done, R = self.explore(ob, done)
  File "/home/liubo/deeprl_network/utils.py", line 156, in explore
    next_ob, reward, done, global_reward = self.env.step(action)
  File "/home/liubo/deeprl_network/envs/atsc_env.py", line 182, in step
    self._set_phase(action, 'yellow', self.yellow_interval_sec)
  File "/home/liubo/deeprl_network/envs/atsc_env.py", line 516, in _set_phase
    self.sim.trafficlight.setPhaseDuration(node_name, phase_duration)
  File "/home/liubo/virtual-env/py36/lib/python3.6/site-packages/traci/_trafficlight.py", line 283, in setPhaseDuration
    tc.CMD_SET_TL_VARIABLE, tc.TL_PHASE_DURATION, tlsID, phaseDuration)
  File "/home/liubo/virtual-env/py36/lib/python3.6/site-packages/traci/connection.py", line 141, in _sendDoubleCmd
    self._sendExact()
  File "/home/liubo/virtual-env/py36/lib/python3.6/site-packages/traci/connection.py", line 109, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: The phase duration must be given as an integer.
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).

**Comment by cts198859** [comment]
what is the SUMO version? please try to install SUMO using `setup_sumo.sh`.
