### ISSUE TITLE
size mismatch when running environent

### ISSUE THREAD

**Issue by Jasqine** [cts198859/deeprl_network#9]
When I run the given models in ATSC Monaco(didn't change any code), error appears as follow:
'RuntimeError: size mismatch, m1: [1 x 56], m2: [48 x 64] at /opt/conda/conda-bld/pytorch_1579022071601/work/aten/src/TH/generic/THTensorMath.cpp:136'

 the complete error is:
'
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    train(args)
  File "main.py", line 104, in train
    trainer.run()
  File "/home/ziqi/deeprl_network/utils.py", line 218, in run
    ob, done, R = self.explore(ob, done)
  File "/home/ziqi/deeprl_network/utils.py", line 151, in explore
    policy, action = self._get_policy(ob, done)
  File "/home/ziqi/deeprl_network/utils.py", line 115, in _get_policy
    policy = self.model.forward(ob, done, self.ps)
  File "/home/ziqi/deeprl_network/agents/models.py", line 271, in forward
    actions, out_type)
  File "/home/ziqi/deeprl_network/agents/policies.py", line 221, in forward
    h, new_states = self._run_comm_layers(ob, done, fp, self.states_fw)
  File "/home/ziqi/deeprl_network/agents/policies.py", line 341, in _run_comm_layers
    s_i = self._get_comm_s(i, n_n, x, h, p)
  File "/home/ziqi/deeprl_network/agents/policies.py", line 486, in _get_comm_s
    return F.relu(self.fc_x_layers[i](torch.cat([x[i].unsqueeze(0), nx_i], dim=1))) + \
  File "/root/anaconda3/envs/py35pt/lib/python3.5/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/py35pt/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/root/anaconda3/envs/py35pt/lib/python3.5/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
'

**Comment by cts198859** [comment]
Thanks for catching the bug. The pytorch version was not fully tested. I have pushed the bug fix to `pytorch` branch, please let me know if you still have problem to run it.
